
project_id = "rzzywdulzfyycivwwfsd"

# Migration function
[functions.migrate-agent-data]
verify_jwt = true

# Keep other functions
[functions.get_calls_per_day]
verify_jwt = true

[functions.get-elevenlabs-calls]
verify_jwt = true

[functions.sync-elevenlabs-conversations]
verify_jwt = true

[functions.elevenlabs-diagnostic]
verify_jwt = true

[functions.sync-elevenlabs-history]
verify_jwt = true

[functions.sync-elevenlabs-periodic]
verify_jwt = true

[functions.sync-calls-elevenlabs]
verify_jwt = true

[functions.get-call]
verify_jwt = true

[functions.get-call-audio]
verify_jwt = true

[functions.get-calls]
verify_jwt = true

[functions.calculate_customer_stats]
verify_jwt = true

[functions.get-stats]
verify_jwt = true

[functions.get-customer-stats]
verify_jwt = true

[functions.generate-summary]
verify_jwt = true

[functions.generate-summary-fallback]
verify_jwt = true

[functions.generate-summary-anthropic]
verify_jwt = true

[functions.system-diagnostic]
verify_jwt = true

[functions.fix-security-issues]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = true

[functions.api-monitor]
verify_jwt = true

[functions.api-docs]
verify_jwt = true

[functions.elevenlabs-call-audio]
verify_jwt = true

[functions.get-elevenlabs-call-details]
verify_jwt = true
