
project_id = "rzzywdulzfyycivwwfsd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[realtime]
enabled = true

[edge_functions]
[edge_functions.get-customer-stats]
verify_jwt = false

[edge_functions.elevenlabs-diagnostic]
verify_jwt = false

[edge_functions.elevenlabs-api-test]
verify_jwt = false

[edge_functions.sync-elevenlabs-history]
verify_jwt = false

[edge_functions.elevenlabs-call-audio]
verify_jwt = false

[edge_functions.get-elevenlabs-calls]
verify_jwt = false

[edge_functions.sync-calls-elevenlabs]
verify_jwt = false

[edge_functions.get-calls]
verify_jwt = false

[edge_functions.get-stats]
verify_jwt = false

[edge_functions.sync-elevenlabs-conversations]
verify_jwt = false

[edge_functions.get_calls_per_day]
verify_jwt = false

[edge_functions.elevenlabs-tts]
verify_jwt = false

[edge_functions.generate-summary]
verify_jwt = false

[edge_functions.generate-summary-fallback]
verify_jwt = false

[edge_functions.generate-summary-anthropic]
verify_jwt = false

[edge_functions.system-diagnostic]
verify_jwt = false

[edge_functions.sync-elevenlabs-periodic]
verify_jwt = false

[edge_functions.get-call]
verify_jwt = false
