
project_id = "rzzywdulzfyycivwwfsd"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-call-audio]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-supabase-invitation]
verify_jwt = false

[auth]
# Set OTP expiry to 30 minutes (1800 seconds)
otp_exp = 1800
# Enable leaked password protection
enable_hibp = true
